build:
	docker build -t dnat-ingress-proxy:latest .

tag-register:
	docker tag dnat-ingress-proxy:latest cr.yandex/${CODE_REGISTER}/dnat-ingress-proxy:latest

push-register:
	docker push cr.yandex/${CODE_REGISTER}/dnat-ingress-proxy:latest

