FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o main ./cmd/shortener/main.go

FROM alpine:3.18

WORKDIR /app

COPY --from=builder /app/main .

COPY .env .

RUN mkdir logs/

EXPOSE 8080

CMD ["./main"]
