FROM golang:1.25-alpine as build

WORKDIR /app
COPY . .

RUN go mod download

RUN CGO_ENABLED=0 go build -o main ./cmd/shortener/main.go

FROM gcr.io/distroless/static-debian12

COPY --from=build /app/main /
COPY .env .
#RUN mkdir logs/

EXPOSE 8080

CMD ["/main"]
